apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["default/my-nginx"]'
    management.cattle.io/ui-managed: "true"
  creationTimestamp: "2022-01-19T05:53:00Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/targetWorkloadIds: {}
          f:management.cattle.io/ui-managed: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"3a2466da-7290-4402-8ce0-cb62f03a0224"}:
            .: {}
            f:apiVersion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:workload.user.cattle.io/workloadselector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: rancher
    operation: Update
    time: "2022-01-19T05:53:00Z"
  name: my-nginx
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: Deployment
    name: my-nginx
    uid: 3a2466da-7290-4402-8ce0-cb62f03a0224
  resourceVersion: "7381462"
  uid: d69085c3-547f-4a75-ad47-860f43a075fb
spec:
  clusterIP: 10.43.136.186
  clusterIPs:
  - 10.43.136.186
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: myport
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-my-nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
